# Dictionary mapping typos and abbreviations to their corrected versions

corrections = {
    'sdh': 'sudah',
    'ht': 'hipertensi',
    'tdk': 'tidak',
    'sc': 'sesar',
    'op':'operasi',
    'ca': 'cancer',
    'yg': 'yang',
    'spt': 'seperti',
    'ngga': 'tidak',
    'post': 'setelah',
    'bln': 'bulan',
    'tgl': 'tanggal',
    'kol': 'cholesterol',
    'dg': 'dengan',
    'sp': 'spesialis',
    'sehabis': 'setelah',
    'blm': 'belum',
    'dr': 'dari',
    'ket': 'keterangan',
    'mme': 'mamae',
    'riw': 'riwayat',
    'bisop': 'bisoprolol',
    'nrocos': 'berair',
    'sept': 'september',
    'anget': 'panas',
    'nggreges': 'menggigil',
    'dingin': 'menggigil',
    'demam': 'panas',
    'mens' : 'menstruasi',
    'bimpet': 'tersumbat',
    'mampet': 'tersumbat',
    'nyesek': 'sesak',
    'fam': 'fibroadenoma mamae',
    'kll': 'kecelakaan lalu lintas',
    'dbn': 'dalam batas normal',
    'jempol': 'ibu jari',
    'kemaluan': 'kelamin',
    'anget': 'panas',
    'demam': 'panas',
    'boyok': 'punggung',
    'flu': 'pilek',
    'sebah': 'kembung'
}